### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by fabaff** [ashishb/adb-enhanced#106]
The tool is not usable after an installation from PyPI with `pip`. In a `venv`:

```bash
$ pip3 install adb-enhanced
Collecting adb-enhanced
  Downloading https://files.pythonhosted.org/packages/d1/f2/1a107465266ace455d0b04fecfd108d352a205abad30641c66f041b41645/adb_enhanced-2.5.2-py3-none-any.whl
Collecting future (from adb-enhanced)
[...]
  Stored in directory: /home/test/.cache/pip/wheels/d7/69/b4/3200b95828d1f0ddb3cb5699083717f4fdbd9b4223d0644c57
Successfully built psutil
Installing collected packages: future, docopt, asyncio, psutil, adb-enhanced
Successfully installed adb-enhanced-2.5.2 asyncio-3.4.3 docopt-0.6.2 future-0.18.2 psutil-5.7.0
WARNING: You are using pip version 19.1.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ adbe doze on
Traceback (most recent call last):
  File "/home/test/Documents/repos/adbe/bin/adbe", line 6, in <module>
    from adbe.main import main
ModuleNotFoundError: No module named 'adbe'
```

**Comment by ivanmorgillo-onefootball** [comment]
I'm having some problem as well.
I'm running OSX Catalina (10.15.1 (19B88))

```
➜  ✗ sudo pip3 install adb-enhanced
Collecting adb-enhanced
  Using cached adb_enhanced-2.5.2-py3-none-any.whl (9.2 kB)
Requirement already satisfied: asyncio in /usr/local/lib/python3.7/site-packages (from adb-enhanced) (3.4.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.7/site-packages (from adb-enhanced) (5.6.7)
Requirement already satisfied: docopt in /usr/local/lib/python3.7/site-packages (from adb-enhanced) (0.6.2)
Requirement already satisfied: future in /usr/local/lib/python3.7/site-packages (from adb-enhanced) (0.18.2)
Installing collected packages: adb-enhanced
Successfully installed adb-enhanced-2.5.2
➜  ✗ adbe
Traceback (most recent call last):
  File "/usr/local/bin//adbe", line 5, in <module>
    from adbe.main import main
ModuleNotFoundError: No module named 'adbe'
➜  ✗
```

**Comment by ashishb** [comment]
@ivanmorgillo-onefootball I am on Mac OS 10.15.4 and failing to reproduce this via `sudo pip3 uninstall adb-enhanced && sudo pip3 install adb-enhanced`

@fabaff Thanks, I can reproduce this problem. 2.4.0 is the last working version. You can use ` pip3 install adb-enhanced==2.4.0` which I diagnose and fix this issue.

**Comment by ashishb** [comment]
Alright guys, I did some major code cleanup and fixed the problem(though not fully sure how :( )
Please try out 2.5.4
I tried it inside a virtual machine as well as venv to verify the installation works - https://pypi.org/project/adb-enhanced/2.5.4/#files

**Comment by fabaff** [comment]
Thanks for the update.

**Comment by ashishb** [comment]
@fabaff Can you confirm that its working, so that, I can close this issue?

**Comment by ashishb** [comment]
Closing the issue for now. Please re-open if there are installation problems.
